### ISSUE TITLE
[game] Locks up/freezes when joining Special Forces server

### ISSUE THREAD

**Issue by cetteup** [B2BF/Issues#17]
While launching `xpack` now works fine, joining servers does not. The game just freezes entirely. It only started to load into the map once after what felt like several minutes, but I got kicked for modified content. Looking at a packet capture, there's what seems to be slightly less communication between the game and the server before they start only exchanging 12/16 byte packet pairs (which I believe could just be "I'm loading"). However, looking at the player list on the server I never see my account show up. I do see a connecting player in the console though.

Tested with =DOG= and \*BF2L\* servers.

**Comment by cetteup** [comment]
Seems to _not_ be related to the game files. Joining servers works perfectly fine with `dinput8.dll` removed and the same game install patched for OpenSpy.

**Comment by matthias-hoste** [comment]
Fixed
